apiVersion: apps/v1
kind: Deployment
metadata:
  name: griffon
  labels:
    exivity.k8s/component: griffon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: griffon
      {{- include "exivity.default_labels" . | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: griffon
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: exivity-griffon-config
      - name: config-file
        configMap:
          name: app-config-default
      - name: log
        persistentVolumeClaim:
          claimName: exivity-griffon-log
      containers:
      - name: griffon
        image: {{ .Values.images.griffon }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: config
          mountPath: /exivity/home/system/config
        - name: config-file
          mountPath: /exivity/home/system
        - name: log
          mountPath: /exivity/home/log/griffon
      imagePullSecrets:
      - name: ghcr
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-griffon-config
  labels:
    exivity.k8s/component: griffon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-griffon-log
  labels:
    exivity.k8s/component: griffon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
