apiVersion: apps/v1
kind: Deployment
metadata:
  name: horizon
  labels:
    exivity.k8s/component: horizon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: horizon
      {{- include "exivity.default_labels" . | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: horizon
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
      - name: config
        configMap:
          name: app-config-horizon
      - name: log
        persistentVolumeClaim:
          claimName: exivity-horizon-log
      containers:
      - name: horizon
        image: {{ .Values.images.horizon }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: config
          mountPath: /exivity/home/system
        - name: log
          mountPath: /exivity/home/log/horizon
        - name: log
          mountPath: /exivity/home/log/merlin
      imagePullSecrets:
      - name: ghcr
---
# add templated configmap providing the service with the required config.json
{{- include "exivity.config" (dict "Values" .Values "appname" "horizon" "path" "/bin/horizon" "queue" "BUDGET") }}
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-horizon-log
  labels:
    exivity.k8s/component: horizon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
