{{if not .Values.rabbitmq.useExternalServers}}
apiVersion: v1
kind: Service
metadata:
  name: rabbit
  labels:
    exivity.k8s/component: rabbitmq
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.rabbitmq.port }}
  clusterIP: None
  selector:
    exivity.k8s/component: rabbitmq
    {{- include "exivity.default_labels" . | indent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: exivity-rabbit
  labels:
    exivity.k8s/component: rabbitmq
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: rabbitmq
      {{- include "exivity.default_labels" . | indent 6 }}
  serviceName: rabbit
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: rabbitmq
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      containers:
      - name: exivity-rabbit
        image: {{ .Values.images.rabbitmq }}
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: {{ .Values.rabbitmq.user }}
        - name: RABBITMQ_DEFAULT_PASS
          value: {{ .Values.rabbitmq.password }}
        - name: RABBITMQ_DEFAULT_VHOST
          value: {{ .Values.rabbitmq.vhost }}
{{end}}
