apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exivity.fullname" . }}-rabbitmq-secret
  labels:
    app.kubernetes.io/component: rabbitmq-secret
    {{- include "exivity.labels" . | nindent 4 }}
type: Opaque
data:
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
