apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcript
  labels:
    exivity.k8s/component: transcript
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: transcript
      {{- include "exivity.default_labels" . | indent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: transcript
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: exivity-etl-config
      - name: config-file
        configMap:
          name: app-config-transcript
      - name: exported
        persistentVolumeClaim:
          claimName: exivity-exported
      - name: extracted
        persistentVolumeClaim:
          claimName: exivity-extracted
      - name: import
        persistentVolumeClaim:
          claimName: exivity-import
      - name: log
        persistentVolumeClaim:
          claimName: exivity-transcript-log
      - name: report
        persistentVolumeClaim:
          claimName: exivity-report
      containers:
      - name: transcript
        image: {{ .Values.images.transcript }}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "25m"
            memory: "50Mi"
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        volumeMounts:
        - name: config
          mountPath: /exivity/home/system/config
        - name: config-file
          mountPath: /exivity/home/system
        - name: exported
          mountPath: /exivity/home/exported
        - name: extracted
          mountPath: /exivity/home/system/extracted
        - name: import
          mountPath: /exivity/home/import
        - name: log
          mountPath: /exivity/home/log/transcript
        - name: log
          mountPath: /exivity/home/log/merlin
        - name: report
          mountPath: /exivity/home/system/report
        env:
        - name: EXIVITY_APP_KEY
          valueFrom:
            secretKeyRef:
              name: exivity-secrets
              key: app_key
      imagePullSecrets:
      - name: ghcr
---
# add templated configmap providing the service with the required config.json
{{- include "exivity.config" (dict "Values" .Values "appname" "transcript" "path" "/bin/transcript" "queue" "TRANSFORM") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-transcript-log
  labels:
    exivity.k8s/component: transcript
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
