apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcript
  labels:
    app: exivity
    component: transcript
spec:
  selector:
    matchLabels:
      app: exivity
      component: transcript
  replicas: 1
  template:
    metadata:
      labels:
        app: exivity
        component: transcript
    spec:
      resources:
        requests:
          cpu: "25m"
          memory: "50Mi"
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: exivity-transcript-config
      - name: config-file
        configMap:
          name: app-config-transcript
      - name: extracted
        persistentVolumeClaim:
          claimName: exivity-extracted
      - name: log
        persistentVolumeClaim:
          claimName: exivity-transcript-log
      - name: report
        persistentVolumeClaim:
          claimName: exivity-report
      containers:
      - name: transcript
        image: {{ .Values.images.transcript }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /exivity/home/system/config
        - name: config-file
          mountPath: /exivity/home/system
        - name: extracted
          mountPath: /exivity/home/system/extracted
        - name: log
          mountPath: /exivity/home/log/transcript
        - name: log
          mountPath: /exivity/home/log/merlin
        - name: report
          mountPath: /exivity/home/system/report
        env:
        - name: EXIVITY_APP_KEY
          valueFrom:
            secretKeyRef:
              name: exivity-secrets
              key: app_key
      imagePullSecrets:
      - name: ghcr
---
# add templated configmap providing the service with the required config.json
{{- include "exivity.config" (dict "Values" .Values "appname" "transcript" "path" "/bin/transcript" "queue" "TRANSFORM") }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-transcript-config
  labels:
    app: exivity
    component: transcript
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exivity-transcript-log
  labels:
    app: exivity
    component: transcript
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
